### ISSUE TITLE
Tela Resumo do Pedido

### ISSUE THREAD

**Issue by guilhermekf** [panoramix360/tempero-capixaba#1]
Esta tela deve apresentar o resumo do pedido e um botão para a tela de preenchimento dos dados do cliente
- [x] Resumo do Pedido
- [ ] Botão de Redirecionamento

**Comment by panoramix360** [comment]
Amanhã vou começar a trabalhar nessa feature

**Comment by panoramix360** [comment]
Comecei a exibir uma listView com os itens de pedido que foram selecionados, mas tá dando uns erros no Sugar quando dá back na página
