### ISSUE TITLE
Problema ao scrollar a lista com pratos selecionados

### ISSUE THREAD

**Issue by panoramix360** [panoramix360/tempero-capixaba#4]

**Comment by guilhermekf** [comment]
Estou achando que nosso **holder** e **adptar** talvez tivesse que receber um **ItemPedido** e não **Prato**, ficaria mais facil de tratar o que está faltando. 
Talvez utilizar um viewModel também, gostaria de ver com você as praticas que vamos usar no android.

**Comment by panoramix360** [comment]
Acho que seria legal mesmo reestruturarmos esse reclycler view, hoje você está online?

**Comment by panoramix360** [comment]
Pronto, fiz um commit em cima disso alterei algumas coisas, dá uma olhada
