### ISSUE TITLE
Tela Cardápio Diário

### ISSUE THREAD

**Issue by panoramix360** [panoramix360/tempero-capixaba#6]
- [x] Listar cardápio do dia na página principal
- [x] Permitir selecionar os pratos, quantidade e tamanho da quentinha
- [x] Botão para seguir para a tela de resumo do pedido

**Comment by guilhermekf** [comment]
Acredito que está tudo pronto! Confere por favor!

**Comment by panoramix360** [comment]
Vou conferir, você commitou algo?
