### ISSUE TITLE
Salvar no Banco de dados um Pedido

### ISSUE THREAD

**Issue by panoramix360** [panoramix360/tempero-capixaba#9]
Salvar no banco do SQLite um Pedido e seus itens para que se o usuário fechar sem terminar de realizar o pedido ele já fique com tudo selecionado.
- Se o usuário abrir o app e o Pedido for de outra data, vai ser criado um novo
- Se for da mesma data irá carregar o pedido

**Comment by panoramix360** [comment]
Fiz umas alterações nos detalhes Fogaça!

**Comment by guilhermekf** [comment]
Ok, estou testando isso!

**Comment by panoramix360** [comment]
Não sei se você percebeu mas o Sugar dá merda quando vai pra uma activity e volta pra outra rs

**Comment by guilhermekf** [comment]
Nao vi isso ainda não. Aqui ta indo pra tela de detalhe que não tem nada e volta.

**Comment by panoramix360** [comment]
Deu algum problema com o que eu tava fazendo ontem xD

**Comment by guilhermekf** [comment]
Acho que acertei isso, faltou criar um App hahahahha
Ainda brigando com a data.

**Comment by panoramix360** [comment]
O que é esse TemperoCapixabaApp que você criou?

Tem uma coisa que adicionei no meu ultimo commit que vai mudar a tua lógica.

Eu só salvo no banco os itens de pedido checkados e vi que você só traz os que estão no banco, ou seja, vamos perder uns itens do pedido ae..

To achando que é melhor salvar tudo no banco, as informações do cardápio do dia e tal, porque se o cara quiser dar uma olhada de novo é ruim ele puxar do banco novamente.

É só excluir por dia o cardápio.

**Comment by panoramix360** [comment]
Qaundo eu abri o app 2x seguidas parece que ele excluiu os pratos O.o

**Comment by panoramix360** [comment]
Tem que retestar essa funcionalidade
